export const GIT_REPOSITORY = "GIT_REPOSITORY";
export const COMMAND_LINE = "COMMAND_LINE";
export const USER_REPOSITORIES = "USER_REPOSITORIES";
export const EDITED_REPO = "EDITED_REPO";
export const ADDED_CREDENTIALS = "ADDED_CREDENTIALS";
export const CREDENTIALS_LIST = "CREDENTIALS_LIST";
export const UPDATED_CREDENTIALS = "UPDATED_CREDENTIALS";

export const REGISTERED_USER = "REGISTERED_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const USER_LOGOUT = "USER_LOGOUT";
export const EDITED_USER = "EDITED_USER";
export const SET_USER_DATA = "SET_USER_DATA";




