export const GIT_REPOSITORY = "GIT_REPOSITORY";
export const COMMAND_LINE = "COMMAND_LINE";
export const REGISTERED_USER = "REGISTERED_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const USER_LOGOUT = "USER_LOGOUT";



